version: '2.1'
services:
  playlist-service:
    image: playlist-app
    container_name: playlist-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://playlist:password@db:5432/playlist_db

  db:
    image: postgres
    container_name: playlist-postgres
    restart: always
    environment:
      - POSTGRES_USER=playlist
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=playlist_db
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d
      - ./pginit:/docker-entrypoint.d/create-db.sh
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U playlist -d playlist_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
